### ISSUE TITLE
Problem with bool variable handling

### ISSUE THREAD

**Issue by Nklya** [txn2/p3y#1]
Hello.
First of all, thank you for this project!

I've found a little problem with bool variable handling. 
I tried to setup p3y to proxy Prometheus with TLS.
My docker-compose file looks like:
```
....
  proxy:
    image: txn2/p3y
    ports:
      - '443:8080'
    environment:
      BACKEND: 'http://prometheus:9090'
      USERNAME: 'test'
      PASSWORD: 'test'
      TLS: 'True'
      CRT: 'path_to.crt'
      KEY: 'path_to.key'
```

And when I used `TLS: 'True'`, nothing happened (p3y started without TLS). After looking to code I understand that only `TLS: 'true'` can be used.
https://github.com/txn2/p3y/blob/master/p3y.go#L144 

Maybe it can be handled in code?
Or at least it would be great to add an example to Readme. I can create PR.
